#!/usr/bin/env php
<?php
set_time_limit(0);

require_once __DIR__.'/../vendor/autoload.php';

use Onema\RoboCli\Command\TweetCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new TweetCommand());
$application->run();
       
